add beanie support
jowilf/starlette-admin pull request #185
Opened 2023-05-09 16:19 UTC by opaniagu

I share this PR to be able to support 'beanie' https://beanie-odm.dev/.
Please send feedback and help me test.
Also, GridFs is supported.

2023-05-12 03:07 UTC, jowilf commented
Thank you for submitting the PR! I appreciate your effort and initiative.

I'll do my best to review your changes as soon as possible. In the meantime, you can refer to the test cases for 'odmantic' and 'mongoengine' for testing guidance.

With a quick look, I noticed some comments are in Spanish. To ensure clarity for everyone, it would be better to have them in English. Could you please update those comments?

2023-05-26 19:48 UTC, jowilf requested changes
Hello, thank you again for your PR. After reviewing your code, I have a few suggestions and considerations that we need to address before merging:

* **Flexibility**:
    * It should be possible to run the basic example with only `starlette-admin` and `beanie` as dependencies.
    * Do we really need `mongoengine` as a dependency to use `beanie`?
    * Do we really need `fastapi` as a dependency? I think,  If the code works with starlette, the support for fastapi should be straightforward
    * We should make `Gridfs` optional.
    * To improve extensibility, consider putting the logic of file and image creation inside the File and Image classes, making it easier to override and customize.
    
* **Converters**:
    Version 0.9.0 introduces a new approach for model conversion (#191).I believe the converter for `Beanie` is similar to `ODMantic` as they are both based mostly on Python type annotation. You can refer to ODMantic implementation [here](https://github.com/jowilf/starlette-admin/blob/main/starlette_admin/contrib/odmantic/converters.py)

* **ExpressionField**:
       It is important to support fields lists such as  `[User.id, User.name]`. Take a look at [ExpressionField](https://beanie-odm.dev/api-documentation/fields/#expressionfield) 

* **QueryBuilder**:
The current query builder is not functioning properly. I suggest using [ExpressionField](https://beanie-odm.dev/api-documentation/fields/#expressionfield) to build the queries and letting Beanie handle the conversion to the corresponding database query. For example, using an expression like `User.age > 90` should generate the appropriate database query.

Thanks,

2023-08-14 21:07 UTC, martincpt commented
Would love to see this getting merged. Any update on this?

2023-08-19 19:10 UTC, jowilf commented
Hello @opaniagu ,
Are you still planning to address the review comments? If there's anything I can do to help move it forward, please let me know.

2023-08-21 13:34 UTC, opaniagu commented
> Hello @opaniagu , Are you still planning to address the review comments? If there's anything I can do to help move it forward, please let me know.

Hello, I have little time at the moment. The main problem is that for me (I think) it is already a functional version, but when I was finishing you changed the core and it means I have to review everything from scratch.

2023-08-30 22:42 UTC, jowilf commented
> Hello, I have little time at the moment. The main problem is that for me (I think) it is already a functional version, but when I was finishing you changed the core and it means I have to review everything from scratch.

I truly appreciate your effort, and I'm sorry if the changes inadvertently affected your work. The intention was to improve the conversion process and provide customization options.

2023-09-15 18:42 UTC, ayyshim commented
@opaniagu Any update on this? 

This PR fix and merge could really help alot.

2024-01-02 19:28 UTC, hasansezertasan commented
Hey @opaniagu, I'd like to see this PR to be merged but as far as I can see, the core is outdated. Do you plan to work on this?

2024-01-03 01:15 UTC, opaniagu commented
> Hey @opaniagu, I'd like to see this PR to be merged but as far as I can see, the core is outdated. Do you plan to work on this?

Hi, really now I haven´t time to continue,  maybe someone can take it, and finisih.

2024-01-03 01:41 UTC, hasansezertasan commented
I see, thank you for trying it out 🙏. It might give people some idea. I'm going to play with Beanie in the future. It might be useful.

2025-04-08 03:40 UTC, arnabJ commented
I have started a discussion here: https://github.com/jowilf/starlette-admin/discussions/652

I am working on a stand-alone package for supporting Beanie with starlette-admin. Feedbacks and PRs are welcomed.

2025-05-07 02:43 UTC, jowilf commented
was implemented in #656

2025-05-07 02:43 UTC, closed without merging