Enhance AuthProvider to support oauth2/OIDC flow
jowilf/starlette-admin pull request #221
Opened 2023-07-01 20:07 UTC by jowilf

close #218

2023-07-16 02:08 UTC, simonsax requested changes
I tried it with my project and was able to implement oauth2 authentication. Thanks a lot!

2023-07-16 02:08 UTC, simonsax commented on examples/authlib/provider.py
> +        return await auth0.authorize_redirect(request, redirect_uri)
I had to wrap redirect_uri in str() to avoid an error message -> return await auth0.authorize_redirect(request, str(redirect_uri))

2023-07-16 02:08 UTC, simonsax commented on examples/authlib/provider.py
> +            url=URL(f"https://{AUTH0_DOMAIN}/v2/logout").include_query_params(
this logout domain is provider specific -> my oauth2 provider uses a different endpoint <domain>/logout.do

2023-07-24 13:27 UTC, sternalon commented
Looking forward to this one being merged into the main branch!

2023-07-26 20:17 UTC, merged