Docs: Add spanish translation for /tutorial
jowilf/starlette-admin pull request #53
Opened 2022-12-14 00:05 UTC by rafnixg

- ADD: spanish translation for getting-started
- ADD: spanish translation for configurations 
- ADD: spanish translation for validations 
- ADD: spanish translation for authentication 
- ADD: spanish translation for files 
- ADD: spanish translation for batch actions 
- ADD: spanish translation for multiple-admin

2022-12-14 14:02 UTC, jowilf commented
Hello @rafnixg, 
Thank you for your contribution.
I will take advantage of this PR to setup docs preview with vercel or netlify before merge it.

But I'm also thinking about a better solution to update the translated documentation to follow the main doc. Do you have any suggestion ?

2022-12-19 18:02 UTC, jowilf commented on docs/tutorial/authentication/index.es.md
> +# Autorización de autenticación
This is out of date

2022-12-19 18:07 UTC, jowilf commented on docs/tutorial/configurations/modelview/index.es.md
> +# Configuraciones de ModelView
Miss [https://jowilf.github.io/starlette-admin/tutorial/configurations/modelview/#datatables-extensions](https://jowilf.github.io/starlette-admin/tutorial/configurations/modelview/#datatables-extensions)

2022-12-19 18:22 UTC, jowilf requested changes
Hello @rafnixg, 

Thank you for your work, i made some few comments can you check them ?

Also i notice that mkdocs-static-i18n didn't works well with some mkdocs plugins.

For example, this is what we have in english documentation,

![en](https://user-images.githubusercontent.com/31705179/208492441-56611ee0-a4de-4b3f-b339-33ff89709aac.png)


and this is what we have in spanish documentation

![es](https://user-images.githubusercontent.com/31705179/208492638-8a5cd098-3031-461f-a0fe-4403ca2f0558.png)


This can be a real problem in long term basic, we could be blocked by mkdocs-static-i18n when mkdocs-material release a new version. 

Take a look at this -> https://github.com/squidfunk/mkdocs-material/discussions/2346

2023-10-21 15:34 UTC, hasansezertasan commented
> Hello @rafnixg,
> 
> Thank you for your work, i made some few comments can you check them ?
> 
> Also i notice that mkdocs-static-i18n didn't works well with some mkdocs plugins.
> 
> For example, this is what we have in english documentation,
> 
> ![en](https://user-images.githubusercontent.com/31705179/208492441-56611ee0-a4de-4b3f-b339-33ff89709aac.png)
> 
> and this is what we have in spanish documentation
> 
> ![es](https://user-images.githubusercontent.com/31705179/208492638-8a5cd098-3031-461f-a0fe-4403ca2f0558.png)
> 
> This can be a real problem in long term basic, we could be blocked by mkdocs-static-i18n when mkdocs-material release a new version.
> 
> Take a look at this -> [squidfunk/mkdocs-material#2346](https://github.com/squidfunk/mkdocs-material/discussions/2346)

I have finished the translation process to Turkish Language and I'm facing with same issue. Do you have a fix for it? I'm really excited to share it with the world!

2024-01-02 19:27 UTC, hasansezertasan commented
This PR is quite old and outdated. None of the requested changes are satisfied. @rafnixg are you planning to work on this?

2024-01-02 19:41 UTC, rafnixg commented
I would indeed be interested in supporting the translation, but it wasn't clear to me what the mechanism or the way to proceed would be. You mentioned that mkdocs-static-i18n had issues with other plugins; has this been resolved? I would like to be able to translate and disseminate content in Spanish.

2024-01-02 20:04 UTC, hasansezertasan commented
Happy to see you are still interested in it, I thought this PR was abandoned because you haven't said anything since December 2022.

As far as I know, @jowilf is planning to resolve the issue but it's not there yet. I'm sure the author, seeing two such enthusiastic people in the translation process, you and me, will be motivated to resolve the issue.

Note: I sure tried to resolve the issue myself but couldn't.

2026-08-16 16:25 UTC, jowilf commented
docs translations is removed for now until we have a better system

2026-08-16 16:25 UTC, closed without merging