feat: custom batch with params
jowilf/starlette-admin pull request #61
Opened 2022-12-17 18:08 UTC by giaptx

Hi @jowilf,

I would like to create a PR to try to resolve this issue https://github.com/jowilf/starlette-admin/issues/21#issuecomment-1354299135

I'm not master on frontend, but I try to make this works for my application. The idea is each action will have own form html to custom the input for each action.

Could you have a look? Please feel free to reject if you have any better plan or solution.

Thanks

2022-12-18 09:04 UTC, jowilf commented on starlette_admin/actions.py
> +    form: str = "",
```suggestion
    form: Optional[str] = None,
```

2022-12-18 09:40 UTC, jowilf requested changes
Hello @giaptx, 
It's better idea, we should find a better and easy way to include that,
I made some few comments, please check them

Please add some test, update docstring and the documentation

2022-12-18 09:40 UTC, jowilf commented on starlette_admin/statics/js/list.js
> +
Send form data as [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData)

2022-12-18 09:40 UTC, jowilf commented on starlette_admin/statics/js/list.js
> +
Useful link -> https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects#retrieving_a_formdata_object_from_an_html_form

2022-12-18 09:40 UTC, jowilf commented on examples/custom_actions/models.py
> +        form="""<div class="form-floating mb-3">
I'm not sure but i think a template path could be better here, wdyt?

2022-12-20 03:47 UTC, giaptx commented
Thanks for your review. I will improve when I get time.
Feel free to push to PR if you get time too, because you are best.

2023-03-21 02:39 UTC, jowilf approved these changes

2023-03-21 02:47 UTC, merged

2023-03-21 02:58 UTC, jowilf commented
Thank you all for your contributions